<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    // Runs when you do: php artisan migrate
    // Must run AFTER members and membership_plans migrations
    public function up(): void
    {
        Schema::create('payments', function (Blueprint $table) {
            $table->id('payment_id');

            // Foreign key to members table
            $table->unsignedBigInteger('member_id');
            $table->foreign('member_id')->references('member_id')->on('members');

            // Foreign key to membership_plans table
            $table->unsignedBigInteger('plan_id');
            $table->foreign('plan_id')->references('plan_id')->on('membership_plans');

            $table->decimal('amount', 10, 2);
            $table->enum('payment_method', ['cash', 'gcash']);
            $table->enum('payment_type', ['registration', 'renewal', 'day_pass', 'trainer']);
            $table->date('payment_date');

            // Unique receipt number generated by the stored procedure
            $table->string('receipt_no', 50)->unique();

            // Trigger 1 fires after every insert on this table
            // and auto-sets members.status to active

            $table->timestamps();
        });
    }

    // Runs when you do: php artisan migrate:rollback
    public function down(): void
    {
        Schema::dropIfExists('payments');
    }
};